# lammps input file for insertion trajectory

# VARIABLES
log phase_1.log
variable    data_name       index   run_1.end.data
variable    restart_name    index   phase_1.end.restart
variable    settings_name   index   run_1.in.settings
variable    n_equil         index   300000	  # number of data steps extension segment
variable    coords_freq     index   100 # the frequency that coordinates are prints
variable    thermo_freq     index   100 # the frequency that instantaneous thermodynamic variables are printed to output.
variable    avg_freq        index   100 # the frequency that the thermodynamics averages are printed (to file)
variable    avg_spacing     index   1    # the spacing of snapshots used for average values calculations (printed to file)
variable    Temp            index   0.25
variable    pressure        index   1.0 # Pressure during the simulations
variable    run             index   0

#===========================================================
# GENERAL PROCEDURES
#===========================================================
units		lj
dimension	3	# 3 dimensional simulation
newton		off	# use Newton's 3rd law
boundary	p p p	# periodic boundary conditions 
atom_style	full    # molecular + charge

#===========================================================
# FORCE FIELD DEFINITION
#===========================================================
special_bonds  lj   0.0 0.0 0.0  coul 0.0 0.0 0.0     # NO     1-4 LJ/COUL interactions
pair_style     hybrid lj/cut 2.5 # outer_LJ outer_Coul (cutoff values, see LAMMPS Doc)
bond_style     harmonic             # parameters needed: k_bond, r0
angle_style    harmonic             # parameters needed: k_theta, theta0
kspace_style   none          # long-range electrostatics sum method
pair_modify    shift yes mix arithmetic       # using Lorenz-Berthelot mixing rules

#===========================================================
# SETUP SIMULATIONS
#===========================================================

# READ IN COEFFICIENTS/COORDINATES/TOPOLOGY
variable prev equal (v_run-1)
if "${run} == 0" then &
   "read_data ${data_name}" &
else &
   "read_restart ${prev}.${restart_name}"
include ${settings_name}

# SET RUN PARAMETERS
timestep	0.005		# fs
run_style	verlet 		# Velocity-Verlet integrator
neigh_modify every 1 delay 10 check yes one 10000

compute pot all pe/atom
compute kin all ke/atom

# SET OUTPUTS
thermo_style    custom step temp vol density etotal pe ebond eangle edihed ecoul elong evdwl enthalpy press
thermo_modify   format float %14.6f
thermo ${thermo_freq}

# Declare relevant output variables and create averages fix
variable        my_step equal   step
variable        my_temp equal   temp
variable        my_rho  equal   density
variable        my_pe   equal   pe
variable        my_ebon equal   ebond
variable        my_eang equal   eangle
variable        my_edih equal   edihed
variable        my_evdw equal   evdwl
variable        my_eel  equal   (ecoul+elong)
variable        my_ent  equal   enthalpy
variable        my_P    equal   press
variable        my_vol  equal   vol
variable        my_etot equal   etotal
variable        my_pxx  equal   pxx
variable        my_pyy  equal   pyy
variable        my_pzz  equal   pzz
variable        my_pxy  equal   pxy
variable        my_pxz  equal   pxz
variable        my_pyz  equal   pyz

fix averages all ave/time ${avg_spacing} $(v_thermo_freq/v_avg_spacing) ${thermo_freq} v_my_temp v_my_rho v_my_vol v_my_pe v_my_edih v_my_evdw v_my_eel v_my_ent v_my_P v_my_etot v_my_pxx v_my_pyy v_my_pzz v_my_pxy v_my_pxz v_my_pyz file ${run}.phase_1.thermo format %20.10g

#===========================================================
# RUN EXTENSION
#===========================================================

# Set npt/nvt fix for the runs
fix mom all momentum 1000 linear 1 1 1 angular # Zero out system linear and angular momentum every ps 
fix tmp all nvt temp ${Temp} ${Temp} 0.5 # NVT, nose-hoover 100 fs T relaxation

variable base_comp_rate equal -3e-06
variable ts equal 0.005
variable x_comp_rate equal ${base_comp_rate}/(${base_comp_rate}*${run}*${n_equil}*${ts}+1)
fix compr all deform 1 x erate ${x_comp_rate} y volume z volume
# Create coordinate dump
dump equil all custom ${coords_freq} ${run}.phase_1.lammpstrj id type x y z vx vy vz fx fy fz c_pot c_kin
dump_modify equil sort id

# Run equilibration segment
run		${n_equil}

# Write restart files, cleanup, and exit
write_restart   ${run}.phase_1.end.restart
write_data      ${run}.phase_1.end.data pair ii

# Reset dump and increment
undump equil

# Update run number
variable sub equal (v_run+1)
shell sed -i /variable.*run.*index/s/${run}/${sub}/g phase_1.in.init
